// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK9VhWB12BFyhr8NchzmCaGdkyT1hSbZI',
    appId: '1:279860397824:web:3e02ecd4f1107cf96755e5',
    messagingSenderId: '279860397824',
    projectId: 'flutter-task-3f2fd',
    authDomain: 'flutter-task-3f2fd.firebaseapp.com',
    storageBucket: 'flutter-task-3f2fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdj3Ion65Ic_R6MBkRxNrXMqdDBZ08caA',
    appId: '1:279860397824:android:0b950846f9b4c9ae6755e5',
    messagingSenderId: '279860397824',
    projectId: 'flutter-task-3f2fd',
    storageBucket: 'flutter-task-3f2fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJMHd9qCTGPH5Yd-0cudA3QRSiS6Oywo',
    appId: '1:279860397824:ios:7fd6297dd13971ca6755e5',
    messagingSenderId: '279860397824',
    projectId: 'flutter-task-3f2fd',
    storageBucket: 'flutter-task-3f2fd.appspot.com',
    iosClientId: '279860397824-gphtrikdgkqjfn59jisu8a26dc0c4ueq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJMHd9qCTGPH5Yd-0cudA3QRSiS6Oywo',
    appId: '1:279860397824:ios:15e3058c773d55b56755e5',
    messagingSenderId: '279860397824',
    projectId: 'flutter-task-3f2fd',
    storageBucket: 'flutter-task-3f2fd.appspot.com',
    iosClientId: '279860397824-di97bv8cd20337k65o25iktt0c0t0ssd.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
